{
 "title": "Übersicht",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Raum",
    "query": "SHOW TAG VALUES WITH key = \"topic\""
   }
  ]
 },
 "panels": [
  {
   "title": "Raumstatistik",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "alarm",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(val) from (select last(value) as val from mqtt_consumer group by topic) where val >=2000 and topic =~ /co2$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "warn",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(val) from (select last(value) as val from mqtt_consumer group by topic) where val < 2000 and val >= 1250 and topic =~ /co2$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "okay",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(val) from (select last(value) as val from mqtt_consumer group by topic) where val < 1250 and topic =~ /co2$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Uhrzeit",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Raum ${Raum}",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 8 },
   "repeat": "Raum",
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "co2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT distinct(\"value\") FROM \"mqtt_consumer\" WHERE (\"topic\" =~ /^$Raum$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=~", "value": "/^classroom\\/${Raum}\\/co2$/" }
     ]
    }
   ]
  }
 ]
}